name: Artifacts (Package)

on: 
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  build-artifacts:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      id: checkout-code
      uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Setup problem matcher
      uses: Joshua-Ashton/gcc-problem-matcher@v2

    - name: Build release
      id: build-release
      uses: Joshua-Ashton/arch-mingw-github-action@v8
      with:
        command: |
          pacman -Syu --noconfirm git
          . ./build-master.sh --github --force
          echo "PACKAGE_NAME=$PACKAGE_NAME" >> $GITHUB_ENV

    - name: Create releases
      id: create-releases
      uses: softprops/action-gh-release@v1
      with:
        name: "dxvk-gplasync Automated Build"
        tag_name: ${{ env.PACKAGE_NAME }}
        body_path: INFO.md
        fail_on_unmatched_files: true
        draft: false
        files: |
          ./build/*.tar.gz
          ./build.json
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
